### ISSUE TITLE
Implémenter les requêtes

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/sandbox-python#16]
- [x] écriture
- [x] automatisation (réflexion input/output)
- [x] factorisation des méthodes selon le type de requête

**Comment by Guts** [comment]
Simplifier le code (objet...) et utiliser les méthodes incluses dans le package https://isogeo-api-pysdk.readthedocs.io/en/latest/_apidoc/isogeo_pysdk.isogeo_sdk.html#isogeo_pysdk.isogeo_sdk.Isogeo.search

**Comment by SimonSAMPERE** [comment]
Une classe reposant sur les méthodes du package isogeo-pysdk permet de simplifier la connexion à l'API :
* Renseigner le nom d'un fichier d'authentification (qui doit être stocké dans le même répertoire que le fichier request_api_module.py) suffit à générer une instance de la classe et donc à se connecter à l'API. 
* Une seule méthode permet d'effectuer les requêtes en prenant comme paramètre une chaîne de caractère correspondant au filtre sémantique à exécuter.
* Un paramètre de la méthode de requête à l'API du package isogeo-pysdk permet d'obtenir les tags sous forme de dictionnaire. Cela facilite l'extraction des valeurs de champs de filtre et le peuplement des widgets.
